name: Build Docker Image

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix-shell -p nix-info --run "nix-info -m"
      - name: Build tarball
        run: |
          nix build '.#hello-docker'
          ./result > docker.tar.gz
          du -sh docker.tar.gz
